### ISSUE TITLE
[feature request] Support DNS changing IP address

### ISSUE THREAD

**Issue by AzureMarker** [joeycumines/statsd#4]
**Is your feature request related to a problem? Please describe.**
Similar to https://github.com/cactus/go-statsd-client/issues/40, when the IP behind a domain changes our statsd client starts to fail.

**Describe the solution you'd like**
Add a re-resolve interval setting to refresh the IP address used.

**Describe alternatives you've considered**
Automatically try to re-resolve the IP address if the connection fails.

**Additional context**
https://github.com/cactus/go-statsd-client/issues/40

**Comment by joeycumines** [comment]
Thanks for raising this, that does look like a useful feature to have.

This (and any other connection-related feature) sits outside the scope of the core implementation, but I _am_ happy to have some prebuilt implementations within the `statsd` package. There's one example of this already (though I didn't implement it), namely the `Safeconn` type in `safeconn.go`.

Anyway, yes, this feature will get added at some point, likely in the near(ish) future. My general plan for this is:

1. Add an option to enable the trimming of the last newline (the only special case UDP behavior, outside of connect time) for `WriteCloser` connections
2. Provide an implementation that regularly re-resolves the `net.UDPAddr` based on some trigger(s), and automatically replaces the underlying `net.UDPConn`, as necessary

I expect that, being UDP anyway, there probably isn't any need to add any retry logic for failed writes.

Thoughts @AzureMarker? Particularly re: no retries, and on triggers to replace the conn.

**Comment by AzureMarker** [comment]
That sounds good, thanks for the quick reply!

**Comment by joeycumines** [comment]
v1.3.0 should meet your needs @AzureMarker 

```go
conn, err := statsd.NewUDPConn(network, address, time.Second*30)
if err != nil {
	panic(err)
}
client, err := statsd.New(
	statsd.WriteCloser(conn),
	statsd.TrimTrailingNewline(true), // statsd doesn't like trailing newlines in udp packets
	statsd.UDPCheck(true),            // this enables a guard that will cause statsd.New to error if the target explicitly rejects us
)
if err != nil {
	panic(err)
}
```
